### ISSUE TITLE
Testing panel (skein) blank after running Extension Project test

### ISSUE THREAD

**Issue by angstsmurf** [TobyLobster/Inform#21]
With #13 merged, the Test button now works in extension projects. But it still seems glitchy. After running a test, the Testing panel will be blank and the knots that were visible during the test are gone.

**Comment by TobyLobster** [comment]
I can't replicate this. Do you have a list of steps to replicate?

**Comment by angstsmurf** [comment]
No, I can't seem to reproduce it anymore. Something else must have been broken when I reported it.

**Comment by angstsmurf** [comment]
Oh, wait, I can. Just press the "Testing" tab right after running a test, when the Results view has opened, instead of pressing one of the Transcript links in the view. I'd expect it to show the transcript of the latest test, but instead the view is blank.

**Comment by TobyLobster** [comment]
This should now be fixed.

**Comment by angstsmurf** [comment]
After some cursory testing, it mostly works now, but seems to still happen sometimes. I haven't found a reliable way to reproduce it, though.

**Comment by TobyLobster** [comment]
Note that if an extension has multiple tests, then the test selected in the toolbar will be the skein shown in the Testing tab. If 'Test All' is chosen, then nothing is shown in the Testing tab.

**Comment by angstsmurf** [comment]
Right, I think that is what I was seeing.

**Comment by TobyLobster** [comment]
Ok, thanks for testing this, I'll close this one.
